### ISSUE TITLE
Enhancement: nose should capture stderr

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#305]
I think if the capture plugin is going to capture stdout it might as well capture stderr too.

Anyone who doesn't care about chatty tests' stdout isn't going to care about stderr either.

If it's important for stderr to be preserved there could always be an option to do so, but I think the 
default should be to capture both. FYI py.test captures both

Google Code Info:
Issue #: 165
Author: pjenvey%...@gtempaccount.com
Created On: 2008-02-28T06:19:54.000Z
Closed On: 2008-02-28T15:04:27.000Z

**Comment by djhaskin987** [comment]
+1. Totally need this.

**Comment by jstasiak** [comment]
+1

**Comment by alanhamlett** [comment]
+1

**Comment by 2rs2ts** [comment]
Why not just not capture stderr by default and then have a command line argument to capture? It's very frustrating to have to manually capture stderr for all my tests.

**Comment by FreifunkerEZ** [comment]
I switched to `nosetests` because I knew it would shut up my messy tests. But I had `ArgumentParser` print its help into my pristine output. I was on a wild chase until I figured out, that argparse is nothing special, but simply prints to `stderr`. So, yeah. Please.

In the meantime, I use this Mixin for testing, which pipes STDERR into STDOUT - which gets captured properly. All silent.
``` 
class CaptureStderrInStdout():
    real_stderr = sys.stderr

    @staticmethod
    def setUp() -> None:
        sys.stderr = sys.stdout

    def tearDown(self) -> None:
        sys.stderr = self.real_stderr
```

Use it like so: `class MySupahImportantTestCase (CaptureStderrInStdout, unittest.TestCase):`
