### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by laurentb** [nose-devs/nose#852]
When there are too many tests, the last steps end up in a crash.

This error happens with the weboob project, and it started happening with nose 1.3.4 as we added more tests. Full log with traceback here: http://buildbot.weboob.org/builders/penguin/builds/801/steps/shell/logs/stdio

Removing tests solves the issue, or doing sys.setrecursionlimit(10000) as per http://git.symlink.me/?p=laurentb/weboob.git;a=commitdiff;h=d500abf3361470a9662f49911ed050bda81e5026

Obviously sys.setrecursionlimit(10000) isn't the best way to fix it, and will still crash with even more tests.

**Comment by alon** [comment]
Just chiming in to say I am seeing this issue as well, I used the same workaround (sys.setrecursionlimit). To be more specific, it seems mixedSuites generates a single hierarchical suite with a depth proportional to the number of files which is then run by visitation via ContextSuite.__call__ -> ContextSuite.run -> recursively calling each test in _tests, causing the recursionlimit to be broken.

Solutions seem to include:
1. making ContextSuite.run use it's own stack instead of python's, i.e. rewriting as a non recursive tree visitation; would require some changes to Suite, to return a tree of (setup, method/[children], teardown)
2. making mixedSuites produce a smaller depth tree. I don't yet understand what that function does exactly.

**Comment by alon** [comment]
Can anyone comment about this proposed fix:

https://github.com/ConsumerPhysics/nose/commit/9166b83c636b59d3028fb7588a545b9ba1050d5d

**Comment by alon** [comment]
I've created a pull request for this @jszakmeister : https://github.com/nose-devs/nose/pull/938

**Comment by alon** [comment]
ping.

**Comment by jszakmeister** [comment]
I'll get to it when I get a chance... I've got quite a bit going on in my home life.

**Comment by alon** [comment]
Thanks for letting me know!
