### ISSUE TITLE
--ignore-files option not working

### ISSUE THREAD

**Issue by tdihp** [nose-devs/nose#872]
nose 1.3.4 with python 2.7.6 on Ubuntu 14.04

```
$ nosetests -I application.py
usage: nosetests [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: nosetests --help [cmd1 cmd2 ...]
   or: nosetests --help-commands
   or: nosetests cmd --help

error: option -I not recognized
```

the same goes to --ignore-files and ignore-files in setup.cfg

**Comment by jszakmeister** [comment]
It works for me:

```text
:: nosetests -v
test_bar.test_bar ... ok
test_foo.test_foo ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK
:: nosetests -v -I test_foo.py
test_bar.test_bar ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
:: nosetests -v -I test_bar.py
test_foo.test_foo ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

I suspect you have some other configuration that is getting in the way.

**Comment by tdihp** [comment]
@jszakmeister It's true.

I found it's reproduced when I have a setup.py like this:

```Python
from setuptools import setup

setup(
    name='foobar'
)
```

**Comment by jszakmeister** [comment]
So the problem here is that the `-I` option is clobbering the default setting (this is intentional and mentioned in the help), and the default value ignores files called `setup.py`.  Since the value was clobbered, setup.py is being imported and is being executed.  In this case, distutils doesn't recognize the command line options and exits with the usage information and kills nose in the process.

So there are a couple of ways around this issue.  If you want to continue to use `-I`, then setup a value in your `setup.cfg`:

```text
[nosetests]
with-coverage = true
cover-inclusive = true
ignore-files = (?:^\.|^_,|^setup\.py$)
```

This setting is the same as Nose's default, but now that it's set, any other value you specify on the command line will be appended.

The other choice is to use the attr plugin to mark up your tests.  Then you can use attribute selection to skip ones you don't want to run.  This is the more common way to avoid specific tests.

Finally, if there's just a handful of tests you really want to run, you can just specify them directly on the command line.  But I suspect from your usage that you are just trying to avoid a specific test.

**Comment by tdihp** [comment]
Thanks @jszakmeister.

The reasoning is kinda weird but now I see.

So cover-inclusive imported setup.py because setup.py is not ignored, then it ruined command line args.

**Comment by jszakmeister** [comment]
> So cover-inclusive imported setup.py because setup.py is not ignored, then it ruined command line args.

It's not that it ruined your command line args, it's that importing setup.py causes it to *execute*.  It's like running `python setup.py -I application.py` from within Nose (but not as a separate process).  The usage message and error you see is coming from the `setup()` call in your `setup.py`.

I hope that makes a little more sense.

**Comment by Tarrasch** [comment]
So other's don't need to waste hours of time debugging. Here's the correct regexp to pass to the cli:

    --ignore-files='(^\.|^_|^setup\.py$)'

Source of default: https://github.com/nose-devs/nose/blob/23a3ca8cc1d4c72eec82b421701d248d10d70d0d/nose/config.py#L194-L197
