### ISSUE TITLE
Trying to ignore everything collects duplicate __init__.py modules

### ISSUE THREAD

**Issue by mapleoin** [nose-devs/nose#931]
I was trying to get nose to collect tests in modules starting with one underscore. (We have this convention that we name the test modules the same as the modules they are testing, so if I'm testing `foo.py`, I would have a `test/foo.py` module and if I have code in `foo/__init__.py`, I would have a `test/foo/__init__.py` test module file. 

After some googling, it seemed the way to go was to set `ignore-files` to a REGEXP which wouldn't match:

```
$ cat setup.cfg 
[nosetests]
all-modules=1
ignore-files=DONTIGNORE
```

But now the tests in the `__init__.py` file get run twice:

```
$ ls
__init__.py  __init__.pyc  _other_test.py  _other_test.pyc  setup.cfg

$ cat __init__.py
import unittest

class TestDunder(unittest.TestCase):
    def test_one(self):
        pass

$ cat _other_test.py
import unittest

class TestOther(unittest.TestCase):
    def test_two(self):
        pass

$ nosetests -v
test_one (noseexample.TestDunder) ... ok
test_one (noseexample.TestDunder) ... ok
test_two (noseexample._other_test.TestOther) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.002s

OK
```

What I found was that changing ignore_files, to ignore files starting with double underline actually does the trick, by just ignoreing the duplicate:

```
$ nosetests --ignore-files=^__ -v 
test_one (noseexample.TestDunder) ... ok
test_two (noseexample._other_test.TestOther) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK
```

```
$ nosetests --version
nosetests version 1.3.7
$ python --version
Python 2.7.5
```

**Comment by jszakmeister** [comment]
I have a fix for this in #957, but I don't intend to cut a release any time soon.  The problem here is that you specified all modules should be included in the setup.cfg, but didn't do anything to ignore __init__.py files.  Unfortunately, the interaction between say that causes the __init__.py files to picked up, even though we already loaded by importing it as a package.  When the ignores doesn't ignore __init__.py files, the all modules plugin says it wants the file and so we import it again.

To fix this, I'm not letting other plugins make the decision about the __init__.py files.  Instead, we'll filter it off in the import from dir case and only collect it as a package.
